# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-janitor" do
  name "git-janitor"
  desc "A fast, interactive TUI for cleaning up local Git branches."
  homepage "https://github.com/jvherck/git-janitor"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-janitor"

  on_macos do
    url "https://github.com/jvherck/git-janitor/releases/download/v#{version}/git-janitor_Darwin_all.tar.gz"
    sha256 "47f7aca6210dccd701941c6755df4e8c8c6ed7f52c5d478a66f6e6a0a010f584"
  end

  on_linux do
    on_intel do
      url "https://github.com/jvherck/git-janitor/releases/download/v#{version}/git-janitor_Linux_x86_64.tar.gz"
      sha256 "3900ed47b841a83a82941431ef64485e82b651d0d89be69e3f8396883012fe6f"
    end
    on_arm do
      url "https://github.com/jvherck/git-janitor/releases/download/v#{version}/git-janitor_Linux_arm64.tar.gz"
      sha256 "5991ec15be15b2a64709318b1571750562e5d410f445761b1e5cd54862cfcfed"
    end
  end

  # No zap stanza required
end
