# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-janitor" do
  name "git-janitor"
  desc "A fast, interactive TUI for cleaning up local Git branches."
  homepage "https://github.com/jvherck/git-janitor"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-janitor"

  on_macos do
    url "https://github.com/jvherck/git-janitor/releases/download/v#{version}/git-janitor_Darwin_all.tar.gz"
    sha256 "7342650c1887ebdf6eff8c9542809c9c4c8c81aa546c5d24b3b5dd31f761a367"
  end

  on_linux do
    on_intel do
      url "https://github.com/jvherck/git-janitor/releases/download/v#{version}/git-janitor_Linux_x86_64.tar.gz"
      sha256 "c766bfc0d7b0a04333e085e40b5a704370d2e65821c23f01437aa54335efd7e0"
    end
    on_arm do
      url "https://github.com/jvherck/git-janitor/releases/download/v#{version}/git-janitor_Linux_arm64.tar.gz"
      sha256 "41748b9b2a8ce93d679209c6c9b8a75b8e5085849ea5865b19778ce805934740"
    end
  end

  # No zap stanza required
end
